//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public string IDAdmin { get; set; }
        public string IDAccount { get; set; }
        public string NameAdmin { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string NumberPhone { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
