//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHANQUYEN
    {
        public string IDAccount { get; set; }
        public string IDPer { get; set; }
        public bool suspended { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual PERMISSION PERMISSION { get; set; }
    }
}
