//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBCTKMUONSACH
    {
        public string MaBCTKMuonSach { get; set; }
        public string MaTheLoai { get; set; }
        public int SoLuotMuon { get; set; }
        public double TiLe { get; set; }
    
        public virtual BCTKMUONSACH BCTKMUONSACH { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
