//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBCTKTRATRE
    {
        public string MaBCTKTraTre { get; set; }
        public string MaPhieuMS { get; set; }
        public string MaSach { get; set; }
        public int SoNgayTraTre { get; set; }
    
        public virtual BCTKTRATRE BCTKTRATRE { get; set; }
        public virtual PHIEUTRASACH PHIEUTRASACH { get; set; }
    }
}
