//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUMUON
    {
        public string MaPhieuMS { get; set; }
        public string MaSach { get; set; }
        public System.DateTime HanTra { get; set; }
        public string TinhTrangMuon { get; set; }
    
        public virtual PHIEUMUONSACH PHIEUMUONSACH { get; set; }
        public virtual SACH SACH { get; set; }
        public virtual PHIEUTRASACH PHIEUTRASACH { get; set; }
    }
}
