//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCGIA()
        {
            this.PHIEUMUONSACHes = new HashSet<PHIEUMUONSACH>();
            this.PHIEUTHUTIENPHATs = new HashSet<PHIEUTHUTIENPHAT>();
        }
    
        public string MaDocGia { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public System.DateTime NgayLapThe { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public string MaLoaiDocGia { get; set; }
        public string IDAccount { get; set; }
        public string SDT { get; set; }
        public decimal TongNo { get; set; }
        public string GioiThieu { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual LOAIDOCGIA LOAIDOCGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUONSACH> PHIEUMUONSACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIENPHAT> PHIEUTHUTIENPHATs { get; set; }
    }
}
