//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV_DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int MaThamSo { get; set; }
        public int TuoiToiDa { get; set; }
        public int TuoiToiThieu { get; set; }
        public int ThoiHanThe { get; set; }
        public int KhoangCachXB { get; set; }
        public int SoNgayMuonMax { get; set; }
        public int SoSachMuonMax { get; set; }
        public decimal TPTraTreMotNgay { get; set; }
        public int SoLuongTheLoaiMax { get; set; }
        public int SoLuongTacGia { get; set; }
    }
}
